FROM golang:1.11.2-alpine3.8 AS build

WORKDIR /go/src/app
COPY . .
RUN apk update \
  && apk add --no-cache git \
  && go get github.com/go-sql-driver/mysql

RUN go install -v app

FROM alpine:3.8
COPY --from=build /go/bin/app /usr/local/bin/
CMD ["app"]